name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci --legacy-peer-deps

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build
        env:
           NEXT_PUBLIC_API_URL: "https://api.man2man.xyz"
           NODE_OPTIONS: "--max_old_space_size=2048"

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './frontend/out/'
          server-dir: '/home/zizocom/public_html/'
          dry-run: false
